baseURL = "http://examplesite.org/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Custom SPV Documents"
[markup.goldmark.renderer]
unsafe = true
